"""
Agentic Custom Signal Backtest — OpenAI / GPT-4o mini.

Demonstrates the "bring your own signal" workflow: a signal computed
entirely outside this library (standing in for a user's own proprietary
alpha model) is handed to the agent, which backtests it via
run_custom_signal_backtest / run_signal_panel_backtest and then sizes a
position from the resulting statistics — the library never generates or
second-guesses the signal itself, it only backtests and combines it.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import json

import pandas as pd
from _agent_utils import _header, _log, route_request, run_agent, setup_logging

from standard_quant_tools.data.factory import DataFactory

# ── Configuration ──────────────────────────────────────────────────
OPENAI_API_KEY = ""  # Replace with your key
MODEL = "gpt-4o-mini"

SYMBOL = "AAPL"
START_DATE = "2022-06-01"
END_DATE = "2023-06-01"

PANEL_TICKERS = ["AAPL", "MSFT", "GOOGL"]
PANEL_START = "2023-01-01"
PANEL_END = "2023-06-01"


def _acceleration_signal(close: pd.Series) -> pd.Series:
    """
    Stand-in for a user's own proprietary alpha model: long when 5-day
    momentum exceeds 20-day momentum (short-term acceleration), flat
    otherwise. This is deliberately NOT one of the library's built-in
    indicator strategies — the point of this example is that the library
    never needs to know how the signal was produced.
    """
    accel = close.pct_change(5) - close.pct_change(20)
    return (accel > 0).astype(int)


def _signal_dict(symbol: str, start: str, end: str) -> dict:
    """Fetch OHLCV and compute the toy external signal as a {date: value} map."""
    provider = DataFactory.get_provider()
    df = provider.get_ohlcv(symbol, start, end)
    sig = _acceleration_signal(df["Close"])
    return {str(d.date()): float(v) for d, v in sig.items()}


SYSTEM_PROMPT = """You are a quantitative analyst assistant. The user will hand you
a pre-computed trading signal (already generated by their own model) as raw
JSON data embedded in the request — do not regenerate, second-guess, or
replace it with a built-in indicator strategy of your own.

Your job:
1. Call run_custom_signal_backtest (or run_signal_panel_backtest for a
   multi-ticker signal) with the exact signal data provided.
2. Report the backtest statistics plainly (Sharpe, total return, win rate,
   number of trades, max drawdown).
3. Use get_position_size to size a position from the resulting win rate and
   average trade return — this is real risk sizing, not a demo number.
4. Never call run_sma_backtest / run_rsi_backtest / run_macd_backtest /
   run_bollinger_backtest / run_regime_adaptive_backtest for this request —
   the user's signal already IS the strategy; your job is only to evaluate
   and size it.
"""


if __name__ == "__main__":
    log_file = setup_logging("agent_custom_signal_openai")

    _header("Agentic Custom Signal Backtest — GPT-4o mini")
    _log("Log file", str(log_file))

    single_signal = _signal_dict(SYMBOL, START_DATE, END_DATE)
    panel_signal = {t: _signal_dict(t, PANEL_START, PANEL_END) for t in PANEL_TICKERS}

    _log("Symbol", f"{SYMBOL}  |  {START_DATE} to {END_DATE}")
    _log("Panel tickers", ", ".join(PANEL_TICKERS))
    _log("Signal points (single)", str(len(single_signal)))

    user_request = f"""
I have my own alpha model. Here is its output for {SYMBOL} from {START_DATE}
to {END_DATE} — a signal value per trading day (1 = long, 0 = flat, -1 = short):

{json.dumps(single_signal)}

1. Backtest this exact signal on {SYMBOL} using run_custom_signal_backtest.
2. Then use get_position_size with a $100,000 account, risking 1% per trade,
   using the backtest's win rate and average trade return to size the position.

Separately, here is the same model's output across a small universe
({', '.join(PANEL_TICKERS)}) from {PANEL_START} to {PANEL_END}:

{json.dumps(panel_signal)}

3. Backtest this panel with run_signal_panel_backtest using equal weights,
   and tell me the portfolio-level Sharpe ratio and which ticker contributed
   the strongest individual result.

Report all three results clearly, with the exact numbers from each tool call.
""".strip()

    routed_categories = route_request(user_request, api_key=OPENAI_API_KEY, model=MODEL)

    result = run_agent(
        system_prompt=SYSTEM_PROMPT,
        user_request=user_request,
        api_key=OPENAI_API_KEY,
        model=MODEL,
        max_iterations=10,
        categories=routed_categories,
        # a caller-supplied signal is still a backtest.
        # The router still narrows WITHIN the runtime; the runtime
        # is what makes the narrowing enforceable rather than
        # advisory. See Documentation/19_runtimes.md.
        registry="backtest+portfolio",
    )

    _header("FINAL REPORT")
    print(result)
